---
title: "HERG-analysis"
author: "Marina Schnell"
date: "2024-05-18"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load-packages}
library(tidyverse)
library(readxl)
library(lubridate)
library(data.table)
library(ggpattern)
```

```{r load-data}
HERG_environment <- read_xlsx("data/thievingHERGnotes.xlsx", sheet = "environment")
HERG_observations <- read_xlsx("data/thievingHERGnotes.xlsx", sheet = "observations")
```

```{r fix-time-environment}
HERG_environment <- HERG_environment %>%
  separate(col = time, into = c("dateWRONG","time"), sep = " ", convert = TRUE) %>%
  mutate(dateWRONG = NULL) %>%
  unite(datetime, c(date, time), sep = " ") %>%
  mutate(datetime, ymd_hms(datetime)) %>%
  mutate(datetime = NULL) %>%
  rename(datetime = `ymd_hms(datetime)`) %>%
  relocate(datetime, .before = temp)
```

```{r tidy-environment}
HERG_environment <- HERG_environment %>%
  mutate(people_path = na_if(people_path, "not_taken")) %>%
  mutate(people_path = as.numeric(people_path)) %>%
  mutate(people_bar = na_if(people_bar, "not_taken")) %>%
  mutate(people_bar = as.numeric(people_bar)) %>%
  mutate(date = as.Date(datetime)) %>%
  mutate(time = as.ITime(datetime))
```

```{r tidy-observations}
HERG_observations <- HERG_observations %>%
  separate(col = time, into = c("dateWRONG","time"), sep = " ", convert = TRUE) %>%
  mutate(dateWRONG = NULL) %>%
  unite(datetime, c(date, time), sep = " ") %>%
  mutate(datetime, ymd_hms(datetime)) %>%
  mutate(datetime = NULL) %>%
  rename(datetime = `ymd_hms(datetime)`) %>%
  relocate(datetime, .before = original) %>%
  mutate(date = as.Date(datetime)) %>%
  mutate(time = as.ITime(datetime))

HERG_observations <- HERG_observations %>%
  mutate(thief = na_if(thief, "none"),
         drop_ht_1 = na_if(drop_ht_1, "none"),
         drop_ht_2 = na_if(drop_ht_2, "none"),
         drop_ht_3 = na_if(drop_ht_3, "none"),
         drop_ht_4 = na_if(drop_ht_4, "none"),
         substrate_1 = na_if(substrate_1, "none"),
         substrate_2 = na_if(substrate_2, "none"),
         substrate_3 = na_if(substrate_3, "none"),
         substrate_4 = na_if(substrate_4, "none"),
         distance_a = na_if(distance_a, "none"),
         distance_b = na_if(distance_b, "none"),
         distance_c = na_if(distance_c, "none"))
```

```{r graph-gull-counts}
HERG_counts <- HERG_environment %>%
  select(date, time, HERG_A, HERG_J) %>%
  pivot_longer(., cols = c(HERG_A, HERG_J),
               names_to = "age_count",
               values_to = "count") %>%
  group_by(date, age_count) %>%
  summarise(mean_count = mean(count))

HERG_counts %>%
  ggplot(mapping = aes(date, mean_count, fill = age_count)) +
  geom_col()+
  scale_fill_manual(values = c("HERG_A" = "darkseagreen2",
                               "HERG_J" = "darkseagreen4"),
                    labels = c("HERG_A" = "Adult",
                               "HERG_J" = "Juvenile")) +
  labs(x = "Date",
       y = "Count (Average)",
       title = "Count of Herring Gulls on the Bar",
       fill = "Age Class")
```
```{r graph-people-counts}
HERG_environment %>%
  select(date, time, people_path, people_bar) %>%
  pivot_longer(., cols = c(people_path, people_bar),
               names_to = "location",
               values_to = "count") %>%
  group_by(date, location) %>%
  summarise(mean_count = mean(count, na.rm = TRUE)) %>%
  ggplot(mapping = aes(date, mean_count, fill = location)) +
  geom_col() +
  scale_fill_manual(values = c("people_bar" = "darkorange2",
                               "people_path" = "darkorange4"),
                    labels = c("people_bar" = "Bar",
                               "people_path" = "Path")) +
labs(x = "Date",
       y = "Mean # of Humans",
       title = "Mean Count of Humans on the Bar",
       fill = "Location")
```

```{r graph-total-stealing-events-unstandardized}
HERG_observations %>%
  filter(thieves_A + thieves_J > 0) %>%
  group_by(date) %>%
  ggplot(mapping = aes(date, fill = original)) +
  geom_bar() +
  scale_fill_manual(values = c("A" = "lightgoldenrod",
                               "J" = "lightgoldenrod4"),
                    labels = c("A" = "Adult",
                               "J" = "Juvenile")) +
labs(x = "Date",
       y = "# Victims",
       title = "Herring Gull Victims",
       fill = "Age Class of Victims")
```

```{r graph-total-stealing-events-standardized}
HERG_observations %>%
  left_join(HERG_counts) %>%
  filter(thieves_A + thieves_J > 0) %>%
  filter(age_count == "HERG_A" & original == "A" |
           age_count == "HERG_J" & original == "J") %>%
  group_by(date, original) %>%
  summarise(stealing_std = n()/mean_count) %>%
  ggplot(mapping = aes(date, stealing_std, fill = original)) +
  geom_col() +
  scale_fill_manual(values = c("A" = "lightgoldenrod",
                               "J" = "lightgoldenrod4"),
                    labels = c("A" = "Adult",
                               "J" = "Juvenile")) +
labs(x = "Date",
       y = "# Victims / Mean # Individuals",
       title = "Herring Gull Victims",
       subtitle = "Standardized by Mean Counts",
       fill = "Age Class of Victims")
```

```{r graph-thieves-unstandardized}
HERG_observations %>%
  filter(thieves_A + thieves_J > 0) %>%
  pivot_longer(., cols = c(thieves_A, thieves_J),
               names_to = "age_thieves",
               values_to = "thieves_total") %>%
  group_by(date) %>%
  ggplot(mapping = aes(date, thieves_total, fill = age_thieves)) +
  geom_col() +
  scale_fill_manual(values = c("thieves_A" = "lightblue",
                               "thieves_J" = "lightblue4"),
                    labels = c("thieves_A" = "Adult",
                               "thieves_J" = "Juvenile")) +
  labs(x = "Date",
       y = "Total # Thieves",
       title = "Herring Gull Thieves",
       fill = "Age Class of Thieves")
```

```{r graph-thieves-standardized}
HERG_observations %>%
  left_join(HERG_counts) %>%
  filter(thieves_A + thieves_J > 0) %>%
  pivot_longer(., cols = c(thieves_A, thieves_J),
               names_to = "age_thieves",
               values_to = "thieves") %>%
  filter(age_count == "HERG_A" & age_thieves == "thieves_A" |
           age_count == "HERG_J" & age_thieves == "thieves_J") %>%
  group_by(date, age_thieves) %>%
  summarise(thieves_std = thieves/mean_count) %>%
  ggplot(mapping = aes(date, thieves_std, fill = age_thieves)) +
  geom_col() +
  scale_fill_manual(values = c("thieves_A" = "lightblue",
                               "thieves_J" = "lightblue4"),
                    labels = c("thieves_A" = "Adult",
                               "thieves_J" = "Juvenile")) +
  labs(x = "Date",
       y = "# Thieves / Mean # Individuals",
       title = "Herring Gull Thieves",
       subtitle = "Standardized by Mean Counts",
       fill = "Age Class of Thieves")
```

```{r filter-successful}
HERG_observations %>% 
  filter(stolen == "Y")
```

```{r}
HERG_observations %>%
  filter(thieves_A + thieves_J == 1)
```

```{r graph-incidence-of-stealing-attempts}
HERG_observations %>%
  mutate(attempt = case_when(thieves_A + thieves_J > 0 ~ "Y",
                             thieves_A + thieves_J == 0 ~ "N")) %>%
  group_by(date) %>%
  ggplot(mapping = aes(date, fill = attempt)) +
  geom_bar() +
  scale_fill_manual(values = c("N" = "mediumpurple2",
                               "Y" = "mediumpurple4"),
                    labels = c("N" = "No",
                               "Y" = "Yes")) +
  labs(x = "Date",
       y = "# Foraging Events Observed",
       title = "Incidence of Stealing Attempts during Foraging Events",
       fill = "Stealing Attempt?")
```


``` {r mutate-for-success-graph}

# excluded one observation in which I lost track of prey (not sure if it was stolen or not)
# one observation of N,S: converted to N because in this case I'm looking at outcomes for thieves

HERG_new <- HERG_observations %>%
  filter(thieves_A + thieves_J > 0,
         stolen != "unknown") %>%
  mutate(stolen = case_when(stolen == "N,S" ~ "N",
                            TRUE ~ stolen)) %>%
  mutate(successful_A = case_when(stolen == "N" ~ 0,
                                  stolen == "Y" & thief == "A" ~ 1,
                                  stolen == "Y" & thief == "J" ~ 0),
         unsuccessful_A = case_when(stolen == "N" ~ thieves_A,
                                    stolen == "Y" & thief == "A" ~ thieves_A - 1,
                                    stolen == "Y" & thief == "J" ~ thieves_A),
         successful_J = case_when(stolen == "N" ~ 0,
                                  stolen == "Y" & thief == "J" ~ 1,
                                  stolen == "Y" & thief == "A" ~ 0),
         unsuccessful_J = case_when(stolen == "N" ~ thieves_J,
                                    stolen == "Y" & thief == "J" ~ thieves_J - 1,
                                    stolen == "Y" & thief == "A" ~ thieves_J)) %>%
  pivot_longer(., cols = c(successful_A, unsuccessful_A, successful_J, unsuccessful_J),
               names_to = "outcome",
               values_to = "count_outcomes")
```

```{r graph-success}

HERG_new %>%
  group_by(date) %>%
  ggplot(mapping = aes(date, count_outcomes, fill = outcome)) +
  geom_col() +
  scale_y_continuous(breaks = c(2, 4, 6, 8, 10), limits = c(0,10)) +
  scale_fill_manual(values = c("successful_A" = "skyblue1",
                               "successful_J" = "dodgerblue4",
                               "unsuccessful_A" = "gray70",
                               "unsuccessful_J" = "gray30"),
                    labels = c("successful_A" = "Successful Adult",
                               "successful_J" = "Successful Juvenile",
                               "unsuccessful_A" = "Unsuccessful Adult",
                               "unsuccessful_J" = "Unsuccessful Juvenile")) +
  labs(x = "Date",
       y = "# Attempted Thieves",
       title = "Success Rates of Stealing Attempts",
       fill = "Outcome")

```